service:
  ip: 0.0.0.0
  port: 17271
  log_level: INFO
  timeout: 60
doris:
  endpoint: doris:9030
  username: admin
  password: admin
  database: otel
  table_name: otel_traces
  metric_table_name: otel_metrics
  timezone: Asia/Shanghai
